# Nome da sua GitHub Action
name: Generate Snake Animation

# Controles de quando a Action deve rodar
on:
  # Roda automaticamente a cada 12 horas
  schedule:
    - cron: "0 */12 * * *"
  # Permite que você rode essa Action manualmente pela aba Actions
  workflow_dispatch:

# Define as tarefas que a Action irá executar
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Puxa o código do seu repositório
      - uses: actions/checkout@v3

      # Passo 2: Gera a animação da cobrinha
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          # Substitua pelo seu nome de usuário do GitHub
          github_user_name: MiguelRicado
          # Lista de saídas que serão geradas
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Passo 3: Envia os arquivos gerados de volta para o repositório
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
